version: "3.5"

services:
  product-service:
    build:
      context: ./product-service
    ports:
      - 8081:8080

  shopping-cart:
    build:
      context: ./shopping-cart
    ports:
      - 8082:8080
    environment:
      - PRODUCT_SERVICE=http://product-service:8080
    depends_on:
      - product-service

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - shopping-cart

  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    ports:
      - 3000:3000
    volumes:
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./grafana/spring-boot-statistics_rev2.json:/etc/grafana/provisioning/dashboards/spring-boot-statistics_rev2.json
    depends_on:
      - prometheus
