version: "3.5"

services:
  product-service:
    build:
      context: ./product-service
    ports:
      - 8081:8080

  shopping-cart:
    build:
      context: ./product-service
    ports:
      - 8082:8080
    depends_on:
      - product-service
